name: Release-triggered removal of source code

on:
  workflow_dispatch:
    inputs:
      feature:
        description: Released feature name
        required: true
        type: string

env:
  FILE_PATTERN: '*.html'

jobs:
  remove-time-limited:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: echo ${{ inputs.feature }} > feature.txt

      - uses: piyoppi/actions-chiritori@update-chiritori-v1.4.0
        with:
          filepattern: ${{ env.FILE_PATTERN }}
          delimiter-start: "<!--"
          delimiter-end: "-->"
          removal-marker-target-config: "feature.txt"

      - name: 'Commit diff'
        run: |
          git config --global user.email "chiritori-bot@example.com"
          git config --global user.name "chiritori-bot"
          git checkout -b ${{ env.BRANCH_NAME }}
          git add ${{ env.FILE_PATTERN }}
          git commit -m "Remove time-limited by chiritori"
          git push origin ${{ env.BRANCH_NAME }}

      - name: 'Create pull request'
        uses: actions/github-script@v7
        with:
          script: |
            await github.rest.pulls.create({
              owner: 'owner',
              repo: 'owners-repo',
              title: 'Remove time-limited by chiritori',
              head: `${{ env.BRANCH_NAME }}`,
              base: 'main'
            });
