name: Testing actions-cron2docs with whenever

on: workflow_dispatch

jobs:
  update-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true

      - run: bundle install
        working-directory: actions-cron2docs-whenever/

      - run: bundle exec whenever > crontab.txt
        working-directory: actions-cron2docs-whenever/

      - uses: actions/checkout@v3
        with:
          repository: 'piyoppi/actions-sandbox.wiki'
          path: wiki

      - uses: piyoppi/actions-cron2docs@mirrored
        with:
          task_dirs: ${{ github.workspace }}/actions-cron2docs-whenever/src
          relative_path_base_dir: ${{ github.workspace }}/actions-cron2docs-whenever
          cron_file: ./actions-cron2docs-whenever/crontab.txt
          output_filename: ./wiki/docs_from_whenever.md
          document_yaml_filename: ./actions-cron2docs-whenever/docs/job_docs.yml

      - run: |
          git config --global user.email "bot@garakuta-toolbox.com"
          git config --global user.name "piyoppi-bot"
          git add docs_from_whenever.md
          git commit -m 'test commit'
          git push origin master
        working-directory: ./wiki
