name: Update wiki

on: workflow_dispatch

jobs:
  update-wiki:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'piyoppi/actions-sandbox.wiki.git'
          token: ${{ secrets.TOKEN }}
      - run: |
          echo '# test' >> test.md
          git add test.md
          git commit -m 'test commit'
          git push origin main
